config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback', to: 'session#omniauth'
  
  root 'static#home'
  
  get '/signin', to: 'session#new'
  post '/session', to: 'session#create'
  get '/signout', to: 'session#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  delete '/services/:id', to: 'services#destroy'
  delete '/projects/:id', to: 'projects#destroy'

  resources :users, only: [:index, :show]
  resources :projects, only: [:index, :show, :create, :new, :edit, :update] do
    resources :services, only: [:index, :show, :create, :new, :edit, :update]
  end
  
  resources :services, only: [:index, :show, :create, :new, :edit, :update]
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/service.rb
class Service < ApplicationRecord

    validates :name, presence: true

    has_many :service_projects
    has_many :projects, through: :service_projects
    has_many :products
    has_many :details

    accepts_nested_attributes_for :products, :details, allow_destroy: true
    
    

    # def products_attributes=(products_attributes)
    #     products_attributes.values.each do  |product_attributes|
    #         if product_attributes[:name].present?
    #             product = Product.find_or_create_by(product_attributes)
    #             if !self.products.include?(product)
    #                 self.products << product
    #             end
    #         end
    #     end
    # end

    # def details_attributes=(details_attributes)
    #     details_attributes.values.each do |detail_attributes|
    #         if detail_attributes[:title].present?
    #             detail = Detail.find_or_create_by(detail_attributes)
    #             if !self.details.include?(detail)
    #                 self.details << detail
    #             end
    #         end
    #     end
    # end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
    skip_before_action :user_verified, only: [:index, :show]
    def new
        if current_user.employee
            @service = Service.new
            @service.details.build
            3.times do
                @service.products.build
            end
        else
            redirect_to user_path(current_user), alert: "Only employees can create services"
        end
    end
    def create
        @service = Service.new(service_params)
        if @service.valid?
            @service.save
            redirect_to service_path(@service)
        else
            render :new
        end
    end
    def index
        if params[:project_id]
            @project = Project.find_by(id: params[:project_id])
            if @project.nil?
                redirect_to projects_path, alert: "This project is not found."
            else
                @services = @project.services 
            end
        else
            @services = Service.all
        end
    end
    def show
        if params[:project_id]
            @project = Project.find_by(id: params[:project_id])
            @service = @project.services.find_by(id: params[:id])
            if @service.nil?
                redirect_to project_services_path, alert: "Service not found"
            end
        else
            @service = Service.find(params[:id])
        end
    end
    def edit
        if params[:project_id]
            @project = Project.find_by(id: params[:project_id])
            if @project.nil?
                redirect_to project_services_path, alert: 'Project not found'
            else
                @service = @project.services.find_by(id: params[:id])
            end
        else
            @service = Service.find(params[:id])
        end
    end
    def update
        @project = Project.find_by(id: params[:project_id])
        @service = Service.find(params[:id])
        @service.update_attributes(service_params)
        if @project
            redirect_to project_service_path(@project, @service)
        else
            redirect_to service_path(@service)
        end
    end
    def destroy
        @service = Service.find(params[:id]).destroy
        redirect_to root_path
    end
    private
    def service_params
        params.require(:service).permit(
            :name, :duration,
            products_attributes: [:id, :name],
            details_attributes: [:title, :role, :completed, :user_id]
        )
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for [@project, @service] do |f| %>
    <% if @service.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@service.errors.count, "error") %>
                There are some errors. Please correct before proceeding!
            </h2>
            <ul>
                <% @service.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>
        
    <% if User.completed.find_by(id: current_user.id).nil? %>
        <h3>Please complete your account</h3>

            <%= f.fields_for :details do |product_fields| %>
                <div>
                    <%= product_fields.label 'Your title: ' %>
                    <%= product_fields.text_field :title %>
                </div><br>
                <div>
                    <%= product_fields.label 'Your role: ' %>
                    <%= product_fields.text_field :role %>
                </div><br>
                <div>
                    <%= product_fields.label 'Check for completing your employee account: ' %>
                    <%= product_fields.check_box :completed, {}, true, false %>
                </div><br>
                
                <%= product_fields.hidden_field :user_id, value: current_user.id %>

            <% end %>
        <% end %>

        <h3>Service Field</h3>
        <div>
        <%= f.label 'Service Name: ' %>
        <%= f.text_field :name %>
        </div><br>

        <div>
        <%= f.label 'Service Duration: ' %>
        <%= f.select :duration, options_for_select([1,2,3,4,5,6]) %>
        weeks to complete the service
        </div><br>

        <h3>Product(s) Field</h3>
        <%= f.fields_for :products do |product_fields| %>
            <div>
                <%= product_fields.label 'Product Name: ' %>
                <%= product_fields.text_field :name %>
            </div><br>

        <% end %>

        <%= f.submit %>


    <% end %>

app/views/services/edit.html.erb
<div class='left'>
<h1>Edit Your Service</h1>
<%= render 'form' %>
</div>

app/views/services/index.html.erb
<div class='left'>
<h1>Services our company provide:</h1>
<h2>
<ul>
    <% if @project %>
        <% if !@services.empty? %>
            <% @services.each do |service| %>
                <li><%= link_to service.name, project_service_path(@project, service) %></li>
            <% end %>
        <% else %>
            There is a no service associated to this project. 
            Please delete your project and create new one with services
            <%= button_to "Delete Project", project_path(@project), method: :delete %><br>
        <% end %>
    <% else %>
        <% if !@services.empty? %>
            <% @services.each do |service| %>
                <li><%= link_to service.name, service_path(service) %></li>
            <% end %>
        <% else %>
            There is no service created!
        <% end %>
    <% end %>
</ul>
    <% if current_user && current_user.employee %>
        <%= button_to 'Create Service Here', new_service_path, method: 'get' %>
    <% end %>
</h2>
</div>

app/views/services/new.html.erb
<div class='left'>
<h1>Create Your Service</h1>
<%= render 'form' %>
</div>

app/views/services/show.html.erb
<div class='left'>
<h1>Service Name: <%= @service.name %></h1>
<h1>Time to Complete: <%= @service.duration %> weeks</h1>
<h2>Proudcts needed to complete the service:</h2>
<ul>
    <% @service.products.each do |proudct| %>
        <% if !proudct.name.empty? %>
            <h2><li><%= proudct.name %></li><h2>
        <% end %>
    <% end %>
</ul>


<% if current_user && current_user.employee %>
    <%= button_to "Delete Service", service_path(@service), method: :delete %><br>
    <% if @project %>
        <%= button_to "Edit Service", edit_project_service_path(@project, @service), method: :get %>
    <% else %>
        <%= button_to "Edit Service", edit_service_path(@service), method: :get %>
    <% end %>
<% end %>
</div>