config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback', to: 'session#omniauth'
  
  root 'static#home'
  
  get '/signin', to: 'session#new'
  post '/session', to: 'session#create'
  get '/signout', to: 'session#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  delete '/services/:id', to: 'services#destroy'
  delete '/projects/:id', to: 'projects#destroy'

  resources :users, only: [:index, :show]
  resources :projects, only: [:index, :show, :create, :new, :edit, :update] do
    resources :services, only: [:index, :show, :create, :new, :edit, :update]
  end
  
  resources :services, only: [:index, :show, :create, :new, :edit, :update]
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord

    validates :name, presence: true
    validates :name, uniqueness: true
    validates(:description, {:length => {:maximum => 150}})

    belongs_to :user
    has_many :addresses
    has_many :service_projects
    has_many :services, through: :service_projects

    accepts_nested_attributes_for :addresses

    # def addresses_attributes=(addresses_attributes)
    #     addresses_attributes.values.each do |address_attributes|
    #         if address_attributes[:street].present?
    #             address = Address.create_or_find_by(address_attributes)
    #             if !self.addresses.include?(address)
    #                 self.addresses << address
    #             end
    #         end
    #     end
    # end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def new
        @project = Project.new
        @project.addresses.build
    end
    def create
        @project = Project.new(project_params)
        if @project.save
            redirect_to project_path(@project)
        else
            render :new
        end
    end
    def index
        @projects = Project.all
    end
    def show
        @project = Project.find(params[:id])
    end
    def edit
        @project = Project.find(params[:id])
    end
    def update
        @project = Project.find(params[:id])
        @project.update_attributes(project_params)
        redirect_to project_path(@project)
    end
    def destroy
        @project = Project.find(params[:id]).destroy
        redirect_to root_path
    end
    private
    def project_params
        params.require(:project).permit(
            :name, :description, :start_date, :user_id, service_ids:[],
            addresses_attributes: [:id, :street, :line_2, :city, :state, :zipcode])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
    <% if @project.errors.any? %>
        <div id="error_explanation">
            <h2>
                <%= pluralize(@project.errors.count, "error") %>
                There are some errors. Please correct before proceeding!
            </h2>
            <ul>
                <% @project.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
            </ul>
        </div>
    <% end %>

    <%= f.hidden_field :user_id, value: current_user.id %>
    <h3>Project Field</h3>
    <div>
    <%= f.label 'Name:' %>
    <%= f.text_field :name %>
    </div><br>
    <div>
    <%= f.label 'Description:' %><br>
    <%= f.text_area :description %>
    </div><br>
    <div>
    <%= f.label 'Start Date:' %>
    <%= f.date_field :start_date %>
    </div><br>

    <%= f.fields_for :addresses do |address_fields| %>
        <div>
        <%= address_fields.label 'Street:' %>
        <%= address_fields.text_field :street %>
        </div><br>
        <div>
        <%= address_fields.label 'Line 2:' %>
        <%= address_fields.text_field :line_2 %>
        </div><br>
        <div>
        <%= address_fields.label 'City:' %>
        <%= address_fields.text_field :city %>
        </div><br>
        <div>
        <%= address_fields.label 'State:' %>
        <%= address_fields.text_field :state %>
        </div><br>
        <div>
        <%= address_fields.label 'Zip Code:' %>
        <%= address_fields.text_field :zipcode %>
        </div><br>
    <% end %>

    <div>
    <%= f.label 'Select your service:' %>
    <%= f.collection_check_boxes :service_ids, Service.all, :id, :name %>
    </div><br>

    <%= f.submit %>
<% end %>


f.collection_check_boxe

app/views/projects/edit.html.erb
<div class='left'>
<h1>Edit Your Project</h1>
<%= render 'form' %>
</div>

app/views/projects/index.html.erb
<div class='left'>
<h1>Projects</h1>
<h2>
<ul>
    <% projects = @projects.where(user_id: current_user.id) %>
        <% if !projects.empty? %>
            <% projects.each do |project| %>
                <li><%= link_to project.name , project_path(project) %> </li>
            <% end %>
        <% else %>
            There is no project created.
        <% end %>
</ul>
<%= button_to 'Create Project', new_project_path, method: 'get' %>
</h2>
</div>

app/views/projects/new.html.erb
<div class='left'>
<h1>Create Your Project</h1>
<%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div class='left'>
<h1>Project Name: <%= @project.name %></h1>
<h1>Project Description: <%= @project.description %></h1>
<h2>Project Start Date: <%= @project.start_date %></h2>
<h2>Project Address: </h2>
<ul>
    <% @project.addresses.each do |address| %>
        <h2><li>Street: <%= address.street %></li><h2>
        <% if !address.line_2.empty? %>
            <h2><li>Line 2: <%= address.line_2 %></li><h2>
        <% end %>
        <h2><li>City: <%= address.city %></li><h2>
        <h2><li>State: <%= address.state %></li><h2>
        <h2><li>Zip Code <%= address.zipcode %></li><h2>
        <% end %>
</ul>

<h3>Click <%= link_to 'here', project_services_path(@project) %> to see this project's service and products.<h3>

<%= button_to "Delete Project", project_path(@project), method: :delete %><br>
<%= button_to "Edit Project", edit_project_path(@project), method: :get %>
</div>