config/routes.rb
Rails.application.routes.draw do

  get '/auth/:provider/callback', to: 'session#omniauth'
  
  root 'static#home'
  
  get '/signin', to: 'session#new'
  post '/session', to: 'session#create'
  get '/signout', to: 'session#destroy'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  delete '/services/:id', to: 'services#destroy'
  delete '/projects/:id', to: 'projects#destroy'

  resources :users, only: [:index, :show]
  resources :projects, only: [:index, :show, :create, :new, :edit, :update] do
    resources :services, only: [:index, :show, :create, :new, :edit, :update]
  end
  
  resources :services, only: [:index, :show, :create, :new, :edit, :update]
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <nav class="navbar">
          <ul>
            <li><%= link_to 'HOME', root_path, class: 'link_to' %></li>
            <li><%= link_to 'PROJECTS', projects_path, class: 'link_to' %></li>
            <li><%= link_to 'SERVICES', services_path, class: 'link_to' %></li>
            
              <% if !current_user.nil? %>
              <li><%= link_to current_user.name, user_path(current_user), class: 'link_to' %></li>
              <% end %>
            
          </ul>
      </nav>
      
      <% flash.each do |type, msg| %>
        <div class='flash'>
        <h3><%= msg %></h3>
        </div>
      <% end %>
      
    </div>
   
        <%= yield %>
        
        <div id="footer">
        <ul>
          <li><%= button_to "Log in with Google", '/auth/google_oauth2', class: 'buttonTo' %></li>
        
        <% if current_user %>
          <li><%= link_to 'Sign Out', signout_path, class: 'link_to' %></li>
        <% end %>
        <% if !current_user %>
          <li><%= link_to 'Sign In', signin_path, class: 'link_to' %></li>
          <li><%= link_to 'Sign Up', signup_path, class: 'link_to' %></li>
        <% end %>
        
        </ul>
        </div>

      
  </body>
</html>